language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  # install numpy and pandas for full-suite testing
  - pip install numpy
  - pip install pandas
  - pip install -r requirements.txt
  # install pycap
  - pip install -e .
script:
- "nosetests -w test/ -v"
- "cd docs && make html"
